type: serverless-eventgateway-subscription
version: 0.2.0
core: 0.2.x

description: "Manages Event Gateway Subscriptions"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  url:
    type: string
    required: true
    displayName: URL
    description: The Event Gateway URL
    example: http://localhost
  space:
    type: string
    default: default
    displayName: Space
    description: The Event Gateway space which should be used
    example: acme-marketing-space
  accessKey:
    type: string
    required: true
    displayName: Access Key
    description: The access key used to authenticate with the hosted Event Gateway
    example: s0m34c355k3y
  type:
    type: string
    required: true
    displayName: Type
    description: Subscription type (`sync` or `async`)
    example: async
  eventType:
    type: string
    required: true
    displayName: Type
    description: The event type name
    example: user.created
  functionId:
    type: string
    required: true
    displayName: Function ID
    description: The function id which should be used for the subscription
    example: sendEmail
  path:
    type: string
    displayName: Path
    description: The subscriptions path
    example: /acme
  method:
    type: string
    displayName: Method
    description: The subscriptions method
    example: POST

outputTypes:
  subscriptionId:
    type: string
    description: The subscription id
