type: serverless-eventgateway-function
version: 0.2.0
core: 0.2.x

description: "Manages Event Gateway function registrations"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  url:
    type: string
    required: true
    displayName: URL
    description: The Event Gateway URL
    example: http://localhost
  space:
    type: string
    default: default
    displayName: Space
    description: The Event Gateway space which should be used
    example: acme-marketing-space
  accessKey:
    type: string
    required: true
    displayName: Access Key
    description: The access key used to authenticate with the hosted Event Gateway
    example: s0m34c355k3y
  functionId:
    type: string
    required: true
    displayName: Function ID
    description: The function id which is used to register the function
    example: sendEmail
  type:
    type: string
    required: true
    displayName: Type
    description: The function type
    example: awslambda
  provider:
    type: object
    required: true
    displayName: Provider
    description: Function related provider specification
    example: { arn: 'arn:aws:lambda:us-east-1:12345:function:example', region: 'us-east-1' }

outputTypes:
  functionId:
    type: string
    description: The function id which is used to register the function
